import 'package:flutter/material.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedPreviousReadingsWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedPostReadingWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedBottomNavbarWidget2.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedReadingsWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedActionBarWidget2.dart';
import 'package:flutterapp/mowasscoapp/generatedbill_screenwidget/generated/GeneratedRoundButtonWidget3.dart';

/* Frame Bill_Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBill_ScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 857.0,
                child: GeneratedReadingsWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 25.0,
                child: GeneratedPreviousReadingsWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 32.0,
                child: GeneratedRoundButtonWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 257.0,
                child: GeneratedPostReadingWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedActionBarWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomNavbarWidget2(),
              )
            ]),
      ),
    ));
  }
}
