import 'package:flutter/material.dart';
import 'package:flutterapp/mowasscoapp/generatedhome_pagewidget/generated/GeneratedNewHeaderWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedhome_pagewidget/generated/GeneratedBottomNavbarWidget3.dart';
import 'package:flutterapp/mowasscoapp/generatedhome_pagewidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedhome_pagewidget/generated/GeneratedActionBarWidget3.dart';

/* Frame Home_Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_PageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomNavbarWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 25.0,
                child: GeneratedNewHeaderWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 268.0,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedActionBarWidget3(),
              )
            ]),
      ),
    ));
  }
}
