import 'package:flutter/material.dart';
import 'package:flutterapp/mowasscoapp/generatedjisomeepostwidget/generated/GeneratedJisomeeToPostyourreadingsforbillingPleaseEnterYourAccou.dart';
import 'package:flutterapp/mowasscoapp/generatedjisomeepostwidget/generated/GeneratedAmountWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedjisomeepostwidget/generated/GeneratedRoundButtonWidget.dart';

/* Frame jisomeePost
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJisomeePostWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 353.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 64.0,
                child: GeneratedAmountWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 32.0,
                child: GeneratedRoundButtonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 94.0,
                child:
                    GeneratedJisomeeToPostyourreadingsforbillingPleaseEnterYourAccou(),
              )
            ]),
      ),
    ));
  }
}
