import 'package:flutter/material.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedBottomNavbarWidget1.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedBillSummaryWidget1.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedMnthBilHeadWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedFABWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedActionBarWidget1.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedBillSummaryWidget.dart';
import 'package:flutterapp/mowasscoapp/generatedinvoicewidget/generated/GeneratedMnthWidgWidget.dart';

/* Frame Invoice
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInvoiceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 7.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomNavbarWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 817.0,
                child: GeneratedMnthWidgWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -34.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 337.0,
                child: GeneratedBillSummaryWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 56.0,
                child: GeneratedFABWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 38.0,
                child: GeneratedBillSummaryWidget1(),
              ),
              Positioned(
                left: 76.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 43.0,
                child: GeneratedMnthBilHeadWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedActionBarWidget1(),
              )
            ]),
      ),
    ));
  }
}
