import 'package:flutter/material.dart';
import 'package:flutterapp/mowasscoapp/generatedbillquerrywidget/generated/GeneratedRoundButtonWidget1.dart';
import 'package:flutterapp/mowasscoapp/generatedbillquerrywidget/generated/GeneratedQueryyourBillToknowyourpendingwaterbillpleaseenteryoura.dart';
import 'package:flutterapp/mowasscoapp/generatedbillquerrywidget/generated/GeneratedAmountWidget1.dart';

/* Frame billQuerry
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBillQuerryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 353.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 64.0,
                child: GeneratedAmountWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 104.0,
                child:
                    GeneratedQueryyourBillToknowyourpendingwaterbillpleaseenteryoura(),
              ),
              Positioned(
                left: 73.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 32.0,
                child: GeneratedRoundButtonWidget1(),
              )
            ]),
      ),
    ));
  }
}
